# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details 
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
#      - run: 
#            command: mvn -s .circleci/settings.xml clean javadoc:javadoc package site-deploy
#            no_output_timeout: 120m
#      - run: 
#            command: mvn -s .circleci/settings.xml -f jar-pom.xml clean deploy
#            no_output_timeout: 120m
      - run: cd tests;mvn -s ../.circleci/settings.xml clean package
      - run: cd tests/repository/target/products/org.nasdanika.html.tests.product/linux/gtk/x86_64;eclipse > results.txt
      - run: cd tests/site; mvn -s ../../.circleci/settings.xml site-deploy
            

