<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="app" nsURI="urn:org.nasdanika.html.model.app" nsPrefix="org.nasdanika.html.model.app">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Application model."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//Item">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Label is a text and an icon with a tooltip, notification badge, and help dialog. Labels can have children. Label is a base class for Link."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="color"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="help" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Label help text to display in a modal dialog activated by a click on a question mark icon next to the label."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Label text."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Label icon. Treated as URL if contains ``/`` or as a CSS class otherwise. E.g. ``fas fa-wrench`` would be treated as a CSS class."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Label tooltip."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For some label representations specifies that the label shall be displayed as an outline instead of a solid fill."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Notification to display next to the label. E.g. a number of new messages in an inbox."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Label children to build UI elements like trees, lists, navigation bars and drop-downs."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Link URL relative to the ancestor URL or ``base-uri``.&#xA;&#xA;``${{{base-uri}}}`` token can be used in the activator to define the uri relative to the base generation URI (output folder) instead of the parent URI. &#xA;It might be useful it the parent URI is an absolute external URI.&#xA;``${{{base-uri}}}`` ends with a slash, so there is no need to add a slash. E.g. ``${{{base-uri}}}index.html``."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="script binding"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Script to execute on link click (activation)."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="location binding"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="JavaScript which performs binding of the link action."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="script location"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Confirmation to display in a confirmation dialog before action activation to give the user an opportunity to cancel the action. E.g. confirmation of deletion."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SectionStyle">
    <eLiterals name="Auto"/>
    <eLiterals name="ActionGroup" value="1"/>
    <eLiterals name="Card" value="2"/>
    <eLiterals name="CardPill" value="3"/>
    <eLiterals name="CardTab" value="4"/>
    <eLiterals name="Header" value="5"/>
    <eLiterals name="Pill" value="6"/>
    <eLiterals name="Tab" value="7"/>
    <eLiterals name="Table" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="Primary"/>
    <eLiterals name="Secondary" value="1"/>
    <eLiterals name="Success" value="2"/>
    <eLiterals name="Info" value="3"/>
    <eLiterals name="Warning" value="4"/>
    <eLiterals name="Danger" value="5"/>
    <eLiterals name="Light" value="6"/>
    <eLiterals name="Dark" value="7"/>
    <eLiterals name="Body" value="8"/>
    <eLiterals name="Muted" value="9"/>
    <eLiterals name="White" value="10"/>
    <eLiterals name="Black50" value="11"/>
    <eLiterals name="White50" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Application page consisting of several parts - header, navigation bar, navigation panel, content panel, and footer."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//Header"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Page header is displayed on the top of the page."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigationBar" eType="#//NavigationBar"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation bar is displayed below the header."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigationPanel" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation panel is positioned on the left of the content panel below the navigation bar."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentPanel" eType="#//ContentPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Content panel is positioned on the right of the navigation panel below the navigation bar."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footer" eType="#//Footer"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PagePart" eSuperTypes="../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for page parts."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Custom content to display in the part."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//PagePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Page header has a title on the left and a navigation bar on the right."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//Label"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Header title displayed on the left."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation bar elements. Typically links, but can contain custom content, e.g. inline forms."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationBar" eSuperTypes="#//PagePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Navigation bar has a brand and navigation items."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" eType="#//Label"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Brand label displayed on the left."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation items. Typically links, but may contain custom content."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationPanel" eSuperTypes="#//PagePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Navigation panel contains navigation items. Supports several styles."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//NavigationPanelStyle"
        defaultValueLiteral="Auto">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Panel style"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation items. Typically labels and links, but may contain custom content."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentPanel" eSuperTypes="#//PagePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Content panel displays the primary page conent and can have a navigation bar and several navigation panels."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="breadcrumb" upperBound="-1"
        eType="#//Label" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Breadcrumb items. Displayed on the top of the content panel."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="#//Label"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Content title"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation items are displayed to the right of the title below the breadcrumb bar."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation panel to display on the left of the content."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation panel to display on the right of the content."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatLeftNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation panel which float to the left of the content."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatRightNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation panel which floats to the right of the content."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//ContentPanel" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Content sections."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionColumns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Applicable to section style &quot;Card&quot;. Defines how many columns shall be in a row of section cards."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionStyle" eType="#//SectionStyle"
        defaultValueLiteral="Auto">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines how to generate section children."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Footer" eSuperTypes="#//PagePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Footer is displayed below the navigation and content panels."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Footer navigation items."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NavigationPanelStyle">
    <eLiterals name="Auto"/>
    <eLiterals name="Cards" value="1"/>
    <eLiterals name="Tree" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Link">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Actions form a hierarchy. Application pages are generated from actions. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Action unique ID for cross-referencing."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionColumns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Applicable to section style &quot;Card&quot;. Defines how many columns shall be in a row of section cards."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionStyle" eType="#//SectionStyle"
        defaultValueLiteral="Auto">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines how to generate section children."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.html.model.bootstrap/model/bootstrap.ecore#//BootstrapElement"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navigation items are displayed in the footer the root action, in the navigation bar for the principal action, and in the content panel navigation bar for the active action."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Left navigation panel"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Right navigation panel."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatLeftNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Float left navigation panel."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatRightNavigation" eType="#//NavigationPanel"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Float right navigation panel."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anonymous" upperBound="-1"
        eType="#//Action" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Actions which are not shown in the containing action UI, but for which pages are generated and can be explicitly referenced, e.g. from content. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.exec/model/exec.ecore#//resources/Resource"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources referenced by the page. Resource names are resolved relative to the page location."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Inline action's content is displayed instead of an action link in navigation panels."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="location binding script modal"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Inline action's content is displayed in a modal dialog which opens on a click on the action's link."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="location binding script inline"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
