<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bootstrap" nsURI="urn:org.nasdanika.html.bootstrap" nsPrefix="org.nasdanika.html.bootstrap">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A model of Bootstrap elements."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BootstrapCDNFacet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Page facet for adding CDN Bootstrap and Bootswatch stylesheets and scripts to the page for a specific Bootstrap or Bootswatch theme."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="#//Theme">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bootstrap theme for the page."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.html.model/model/html.ecore#//Facet">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.html.model/model/html.ecore#//Page"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Theme" instanceClassName="org.nasdanika.html.bootstrap.Theme"/>
  <eClassifiers xsi:type="ecore:EClass" name="BootstrapElement" abstract="true" eSuperTypes="../../org.nasdanika.html.model/model/html.ecore#//HTMLElement"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="org.nasdanika.html.bootstrap.Color"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DeviceSize" instanceClassName="org.nasdanika.html.bootstrap.DeviceSize"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Direction" instanceClassName="org.nasdanika.html.bootstrap.Direction"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Placement" instanceClassName="org.nasdanika.html.bootstrap.Placement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wrap" eSuperTypes="#//BootstrapElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Wraps an HTML element into a Bootstrap element for applying Bootstrap styles."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="htmlElement" eType="ecore:EClass ../../org.nasdanika.html.model/model/html.ecore#//HTMLElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alert" eSuperTypes="#//BootstrapElement ../../org.nasdanika.html.model/model/html.ecore#//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
</ecore:EPackage>
